#!/usr/bin/env bash
# using ping command to check network speed. kindly run this script and supply your domain name
if [ "$#" -eq 1 ]; then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
