#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
i=0
j=1
while ((i < 13)); do
	echo "Hour: $i"
	while ((j < 60)); do
		echo $j
		((j++))
	done
	j=0
	((i++))
done
