#!/usr/bin/env bash
# update to /etc/hosts file to block facebook.com 
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
a='8.8.8.8	facebook.com'
echo -e ''$a'' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
